// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AliUnipal/chat/internal/models/message"
	"github.com/AliUnipal/chat/internal/service/msgsvc"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMessageService creates a new instance of MessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageService {
	mock := &MessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageService is an autogenerated mock type for the messageService type
type MessageService struct {
	mock.Mock
}

type MessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageService) EXPECT() *MessageService_Expecter {
	return &MessageService_Expecter{mock: &_m.Mock}
}

// CreateMessage provides a mock function for the type MessageService
func (_mock *MessageService) CreateMessage(ctx context.Context, in msgsvc.MessageInput) (uuid.UUID, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, msgsvc.MessageInput) (uuid.UUID, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, msgsvc.MessageInput) uuid.UUID); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, msgsvc.MessageInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MessageService_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MessageService_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - in msgsvc.MessageInput
func (_e *MessageService_Expecter) CreateMessage(ctx interface{}, in interface{}) *MessageService_CreateMessage_Call {
	return &MessageService_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, in)}
}

func (_c *MessageService_CreateMessage_Call) Run(run func(ctx context.Context, in msgsvc.MessageInput)) *MessageService_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 msgsvc.MessageInput
		if args[1] != nil {
			arg1 = args[1].(msgsvc.MessageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageService_CreateMessage_Call) Return(uUID uuid.UUID, err error) *MessageService_CreateMessage_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MessageService_CreateMessage_Call) RunAndReturn(run func(ctx context.Context, in msgsvc.MessageInput) (uuid.UUID, error)) *MessageService_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type MessageService
func (_mock *MessageService) GetMessages(ctx context.Context, chatID uuid.UUID) ([]message.Message, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []message.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]message.Message, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []message.Message); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]message.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MessageService_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MessageService_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
func (_e *MessageService_Expecter) GetMessages(ctx interface{}, chatID interface{}) *MessageService_GetMessages_Call {
	return &MessageService_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, chatID)}
}

func (_c *MessageService_GetMessages_Call) Run(run func(ctx context.Context, chatID uuid.UUID)) *MessageService_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageService_GetMessages_Call) Return(messages []message.Message, err error) *MessageService_GetMessages_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MessageService_GetMessages_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID) ([]message.Message, error)) *MessageService_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}
