// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMessageController creates a new instance of MessageController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageController {
	mock := &MessageController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageController is an autogenerated mock type for the messageController type
type MessageController struct {
	mock.Mock
}

type MessageController_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageController) EXPECT() *MessageController_Expecter {
	return &MessageController_Expecter{mock: &_m.Mock}
}

// CreateMessage provides a mock function for the type MessageController
func (_mock *MessageController) CreateMessage(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MessageController_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MessageController_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MessageController_Expecter) CreateMessage(w interface{}, r interface{}) *MessageController_CreateMessage_Call {
	return &MessageController_CreateMessage_Call{Call: _e.mock.On("CreateMessage", w, r)}
}

func (_c *MessageController_CreateMessage_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MessageController_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageController_CreateMessage_Call) Return() *MessageController_CreateMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MessageController_CreateMessage_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MessageController_CreateMessage_Call {
	_c.Run(run)
	return _c
}

// GetMessages provides a mock function for the type MessageController
func (_mock *MessageController) GetMessages(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MessageController_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MessageController_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MessageController_Expecter) GetMessages(w interface{}, r interface{}) *MessageController_GetMessages_Call {
	return &MessageController_GetMessages_Call{Call: _e.mock.On("GetMessages", w, r)}
}

func (_c *MessageController_GetMessages_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MessageController_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageController_GetMessages_Call) Return() *MessageController_GetMessages_Call {
	_c.Call.Return()
	return _c
}

func (_c *MessageController_GetMessages_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MessageController_GetMessages_Call {
	_c.Run(run)
	return _c
}
