// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewUserController creates a new instance of UserController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserController(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserController {
	mock := &UserController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserController is an autogenerated mock type for the userController type
type UserController struct {
	mock.Mock
}

type UserController_Expecter struct {
	mock *mock.Mock
}

func (_m *UserController) EXPECT() *UserController_Expecter {
	return &UserController_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type UserController
func (_mock *UserController) CreateUser(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// UserController_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserController_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *UserController_Expecter) CreateUser(w interface{}, r interface{}) *UserController_CreateUser_Call {
	return &UserController_CreateUser_Call{Call: _e.mock.On("CreateUser", w, r)}
}

func (_c *UserController_CreateUser_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *UserController_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserController_CreateUser_Call) Return() *UserController_CreateUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserController_CreateUser_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *UserController_CreateUser_Call {
	_c.Run(run)
	return _c
}

// GetUser provides a mock function for the type UserController
func (_mock *UserController) GetUser(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// UserController_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserController_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *UserController_Expecter) GetUser(w interface{}, r interface{}) *UserController_GetUser_Call {
	return &UserController_GetUser_Call{Call: _e.mock.On("GetUser", w, r)}
}

func (_c *UserController_GetUser_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *UserController_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserController_GetUser_Call) Return() *UserController_GetUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserController_GetUser_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *UserController_GetUser_Call {
	_c.Run(run)
	return _c
}

// Login provides a mock function for the type UserController
func (_mock *UserController) Login(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// UserController_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type UserController_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *UserController_Expecter) Login(w interface{}, r interface{}) *UserController_Login_Call {
	return &UserController_Login_Call{Call: _e.mock.On("Login", w, r)}
}

func (_c *UserController_Login_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *UserController_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserController_Login_Call) Return() *UserController_Login_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserController_Login_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *UserController_Login_Call {
	_c.Run(run)
	return _c
}
