// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewChatController creates a new instance of ChatController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatController(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatController {
	mock := &ChatController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ChatController is an autogenerated mock type for the chatController type
type ChatController struct {
	mock.Mock
}

type ChatController_Expecter struct {
	mock *mock.Mock
}

func (_m *ChatController) EXPECT() *ChatController_Expecter {
	return &ChatController_Expecter{mock: &_m.Mock}
}

// CreateChat provides a mock function for the type ChatController
func (_mock *ChatController) CreateChat(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// ChatController_CreateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChat'
type ChatController_CreateChat_Call struct {
	*mock.Call
}

// CreateChat is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ChatController_Expecter) CreateChat(w interface{}, r interface{}) *ChatController_CreateChat_Call {
	return &ChatController_CreateChat_Call{Call: _e.mock.On("CreateChat", w, r)}
}

func (_c *ChatController_CreateChat_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ChatController_CreateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ChatController_CreateChat_Call) Return() *ChatController_CreateChat_Call {
	_c.Call.Return()
	return _c
}

func (_c *ChatController_CreateChat_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *ChatController_CreateChat_Call {
	_c.Run(run)
	return _c
}

// GetChats provides a mock function for the type ChatController
func (_mock *ChatController) GetChats(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// ChatController_GetChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChats'
type ChatController_GetChats_Call struct {
	*mock.Call
}

// GetChats is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ChatController_Expecter) GetChats(w interface{}, r interface{}) *ChatController_GetChats_Call {
	return &ChatController_GetChats_Call{Call: _e.mock.On("GetChats", w, r)}
}

func (_c *ChatController_GetChats_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ChatController_GetChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ChatController_GetChats_Call) Return() *ChatController_GetChats_Call {
	_c.Call.Return()
	return _c
}

func (_c *ChatController_GetChats_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *ChatController_GetChats_Call {
	_c.Run(run)
	return _c
}
