dir: "{{.InterfaceDir}}/mocks"
structname: "{{.InterfaceName | firstUpper}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
all: true
packages:
  github.com/AliUnipal/chat:
    config:
      outpkg: "mocks"
      recursive: true
