// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/AliUnipal/chat/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockChatService is an autogenerated mock type for the ChatService type
type MockChatService struct {
	mock.Mock
}

type MockChatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatService) EXPECT() *MockChatService_Expecter {
	return &MockChatService_Expecter{mock: &_m.Mock}
}

// CreateDirectChat provides a mock function with given fields: ctx, ownerId, participantId
func (_m *MockChatService) CreateDirectChat(ctx context.Context, ownerId uuid.UUID, participantId uuid.UUID) (uuid.UUID, error) {
	ret := _m.Called(ctx, ownerId, participantId)

	if len(ret) == 0 {
		panic("no return value specified for CreateDirectChat")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (uuid.UUID, error)); ok {
		return rf(ctx, ownerId, participantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) uuid.UUID); ok {
		r0 = rf(ctx, ownerId, participantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerId, participantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_CreateDirectChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDirectChat'
type MockChatService_CreateDirectChat_Call struct {
	*mock.Call
}

// CreateDirectChat is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerId uuid.UUID
//   - participantId uuid.UUID
func (_e *MockChatService_Expecter) CreateDirectChat(ctx interface{}, ownerId interface{}, participantId interface{}) *MockChatService_CreateDirectChat_Call {
	return &MockChatService_CreateDirectChat_Call{Call: _e.mock.On("CreateDirectChat", ctx, ownerId, participantId)}
}

func (_c *MockChatService_CreateDirectChat_Call) Run(run func(ctx context.Context, ownerId uuid.UUID, participantId uuid.UUID)) *MockChatService_CreateDirectChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockChatService_CreateDirectChat_Call) Return(_a0 uuid.UUID, _a1 error) *MockChatService_CreateDirectChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_CreateDirectChat_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (uuid.UUID, error)) *MockChatService_CreateDirectChat_Call {
	_c.Call.Return(run)
	return _c
}

// GetDirectChats provides a mock function with given fields: ctx, userId
func (_m *MockChatService) GetDirectChats(ctx context.Context, userId uuid.UUID) ([]models.DirectChat, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetDirectChats")
	}

	var r0 []models.DirectChat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.DirectChat, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.DirectChat); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DirectChat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_GetDirectChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDirectChats'
type MockChatService_GetDirectChats_Call struct {
	*mock.Call
}

// GetDirectChats is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uuid.UUID
func (_e *MockChatService_Expecter) GetDirectChats(ctx interface{}, userId interface{}) *MockChatService_GetDirectChats_Call {
	return &MockChatService_GetDirectChats_Call{Call: _e.mock.On("GetDirectChats", ctx, userId)}
}

func (_c *MockChatService_GetDirectChats_Call) Run(run func(ctx context.Context, userId uuid.UUID)) *MockChatService_GetDirectChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockChatService_GetDirectChats_Call) Return(_a0 []models.DirectChat, _a1 error) *MockChatService_GetDirectChats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_GetDirectChats_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.DirectChat, error)) *MockChatService_GetDirectChats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatService creates a new instance of MockChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatService {
	mock := &MockChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
