// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockUserContext is an autogenerated mock type for the UserContext type
type MockUserContext struct {
	mock.Mock
}

type MockUserContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserContext) EXPECT() *MockUserContext_Expecter {
	return &MockUserContext_Expecter{mock: &_m.Mock}
}

// GetCurrentUserID provides a mock function with given fields: _a0
func (_m *MockUserContext) GetCurrentUserID(_a0 context.Context) uuid.UUID {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentUserID")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func(context.Context) uuid.UUID); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// MockUserContext_GetCurrentUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentUserID'
type MockUserContext_GetCurrentUserID_Call struct {
	*mock.Call
}

// GetCurrentUserID is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockUserContext_Expecter) GetCurrentUserID(_a0 interface{}) *MockUserContext_GetCurrentUserID_Call {
	return &MockUserContext_GetCurrentUserID_Call{Call: _e.mock.On("GetCurrentUserID", _a0)}
}

func (_c *MockUserContext_GetCurrentUserID_Call) Run(run func(_a0 context.Context)) *MockUserContext_GetCurrentUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserContext_GetCurrentUserID_Call) Return(_a0 uuid.UUID) *MockUserContext_GetCurrentUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserContext_GetCurrentUserID_Call) RunAndReturn(run func(context.Context) uuid.UUID) *MockUserContext_GetCurrentUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserContext creates a new instance of MockUserContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserContext {
	mock := &MockUserContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
