// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createChat = `-- name: CreateChat :exec
INSERT INTO chats (id, current_user_id, other_user_id, created_at, updated_at)
VALUES
    ($1, $2, $3, $4, $5),
    ($6, $3, $2, $4, $5)
`

type CreateChatParams struct {
	ID            uuid.UUID    `db:"id"`
	CurrentUserID uuid.UUID    `db:"current_user_id"`
	OtherUserID   uuid.UUID    `db:"other_user_id"`
	CreatedAt     sql.NullTime `db:"created_at"`
	UpdatedAt     sql.NullTime `db:"updated_at"`
	ID_2          uuid.UUID    `db:"id_2"`
}

// CreateChat
//
//	INSERT INTO chats (id, current_user_id, other_user_id, created_at, updated_at)
//	VALUES
//	    ($1, $2, $3, $4, $5),
//	    ($6, $3, $2, $4, $5)
func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.exec(ctx, q.createChatStmt, createChat,
		arg.ID,
		arg.CurrentUserID,
		arg.OtherUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID_2,
	)
	return err
}

const getChat = `-- name: GetChat :one
SELECT id, current_user_id, other_user_id, created_at, updated_at
FROM chats
WHERE id = $1
`

// GetChat
//
//	SELECT id, current_user_id, other_user_id, created_at, updated_at
//	FROM chats
//	WHERE id = $1
func (q *Queries) GetChat(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.queryRow(ctx, q.getChatStmt, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.CurrentUserID,
		&i.OtherUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatsByUser = `-- name: GetChatsByUser :many
SELECT id, current_user_id, other_user_id, created_at, updated_at
FROM chats
WHERE current_user_id = $1
`

// GetChatsByUser
//
//	SELECT id, current_user_id, other_user_id, created_at, updated_at
//	FROM chats
//	WHERE current_user_id = $1
func (q *Queries) GetChatsByUser(ctx context.Context, currentUserID uuid.UUID) ([]Chat, error) {
	rows, err := q.query(ctx, q.getChatsByUserStmt, getChatsByUser, currentUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.CurrentUserID,
			&i.OtherUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
