// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createChatStmt, err = db.PrepareContext(ctx, createChat); err != nil {
		return nil, fmt.Errorf("error preparing query CreateChat: %w", err)
	}
	if q.getChatStmt, err = db.PrepareContext(ctx, getChat); err != nil {
		return nil, fmt.Errorf("error preparing query GetChat: %w", err)
	}
	if q.getChatsByUserStmt, err = db.PrepareContext(ctx, getChatsByUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetChatsByUser: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createChatStmt != nil {
		if cerr := q.createChatStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createChatStmt: %w", cerr)
		}
	}
	if q.getChatStmt != nil {
		if cerr := q.getChatStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChatStmt: %w", cerr)
		}
	}
	if q.getChatsByUserStmt != nil {
		if cerr := q.getChatsByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChatsByUserStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                 DBTX
	tx                 *sql.Tx
	createChatStmt     *sql.Stmt
	getChatStmt        *sql.Stmt
	getChatsByUserStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                 tx,
		tx:                 tx,
		createChatStmt:     q.createChatStmt,
		getChatStmt:        q.getChatStmt,
		getChatsByUserStmt: q.getChatsByUserStmt,
	}
}
