// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Chat struct {
	ID        uuid.UUID `db:"id"`
	UserOneID uuid.UUID `db:"user_one_id"`
	UserTwoID uuid.UUID `db:"user_two_id"`
	CreatedAt time.Time `db:"created_at"`
}

type User struct {
	ID        uuid.UUID      `db:"id"`
	ImageUrl  sql.NullString `db:"image_url"`
	FirstName string         `db:"first_name"`
	LastName  sql.NullString `db:"last_name"`
	Username  string         `db:"username"`
	CreatedAt time.Time      `db:"created_at"`
}
