// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChat = `-- name: CreateChat :exec
INSERT INTO chats (id, user_one_id, user_two_id, created_at)
VALUES
    ($1, $2, $3, $4)
`

type CreateChatParams struct {
	ID        uuid.UUID `db:"id"`
	UserOneID uuid.UUID `db:"user_one_id"`
	UserTwoID uuid.UUID `db:"user_two_id"`
	CreatedAt time.Time `db:"created_at"`
}

// CreateChat
//
//	INSERT INTO chats (id, user_one_id, user_two_id, created_at)
//	VALUES
//	    ($1, $2, $3, $4)
func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.exec(ctx, q.createChatStmt, createChat,
		arg.ID,
		arg.UserOneID,
		arg.UserTwoID,
		arg.CreatedAt,
	)
	return err
}

const getChat = `-- name: GetChat :one
SELECT
    c.id, c.user_one_id, c.user_two_id, c.created_at, u1.id, u1.image_url, u1.first_name, u1.last_name, u1.username, u1.created_at, u1.password, u2.id, u2.image_url, u2.first_name, u2.last_name, u2.username, u2.created_at, u2.password
FROM chats AS c
         JOIN users AS u1 ON c.user_one_id = u1.id
         JOIN users AS u2 ON c.user_two_id = u2.id
WHERE c.id = $1
`

type GetChatRow struct {
	Chat   Chat `db:"chat"`
	User   User `db:"user"`
	User_2 User `db:"user_2"`
}

// GetChat
//
//	SELECT
//	    c.id, c.user_one_id, c.user_two_id, c.created_at, u1.id, u1.image_url, u1.first_name, u1.last_name, u1.username, u1.created_at, u1.password, u2.id, u2.image_url, u2.first_name, u2.last_name, u2.username, u2.created_at, u2.password
//	FROM chats AS c
//	         JOIN users AS u1 ON c.user_one_id = u1.id
//	         JOIN users AS u2 ON c.user_two_id = u2.id
//	WHERE c.id = $1
func (q *Queries) GetChat(ctx context.Context, id uuid.UUID) (GetChatRow, error) {
	row := q.queryRow(ctx, q.getChatStmt, getChat, id)
	var i GetChatRow
	err := row.Scan(
		&i.Chat.ID,
		&i.Chat.UserOneID,
		&i.Chat.UserTwoID,
		&i.Chat.CreatedAt,
		&i.User.ID,
		&i.User.ImageUrl,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Username,
		&i.User.CreatedAt,
		&i.User.Password,
		&i.User_2.ID,
		&i.User_2.ImageUrl,
		&i.User_2.FirstName,
		&i.User_2.LastName,
		&i.User_2.Username,
		&i.User_2.CreatedAt,
		&i.User_2.Password,
	)
	return i, err
}

const getChatsByUser = `-- name: GetChatsByUser :many
SELECT
    c.id, c.user_one_id, c.user_two_id, c.created_at, u1.id, u1.image_url, u1.first_name, u1.last_name, u1.username, u1.created_at, u1.password, u2.id, u2.image_url, u2.first_name, u2.last_name, u2.username, u2.created_at, u2.password
FROM chats AS c
JOIN users AS u1 ON c.user_one_id = u1.id
JOIN users AS u2 ON c.user_two_id = u2.id
WHERE user_one_id = $1 OR user_two_id = $1
`

type GetChatsByUserRow struct {
	Chat   Chat `db:"chat"`
	User   User `db:"user"`
	User_2 User `db:"user_2"`
}

// GetChatsByUser
//
//	SELECT
//	    c.id, c.user_one_id, c.user_two_id, c.created_at, u1.id, u1.image_url, u1.first_name, u1.last_name, u1.username, u1.created_at, u1.password, u2.id, u2.image_url, u2.first_name, u2.last_name, u2.username, u2.created_at, u2.password
//	FROM chats AS c
//	JOIN users AS u1 ON c.user_one_id = u1.id
//	JOIN users AS u2 ON c.user_two_id = u2.id
//	WHERE user_one_id = $1 OR user_two_id = $1
func (q *Queries) GetChatsByUser(ctx context.Context, userOneID uuid.UUID) ([]GetChatsByUserRow, error) {
	rows, err := q.query(ctx, q.getChatsByUserStmt, getChatsByUser, userOneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatsByUserRow
	for rows.Next() {
		var i GetChatsByUserRow
		if err := rows.Scan(
			&i.Chat.ID,
			&i.Chat.UserOneID,
			&i.Chat.UserTwoID,
			&i.Chat.CreatedAt,
			&i.User.ID,
			&i.User.ImageUrl,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.Username,
			&i.User.CreatedAt,
			&i.User.Password,
			&i.User_2.ID,
			&i.User_2.ImageUrl,
			&i.User_2.FirstName,
			&i.User_2.LastName,
			&i.User_2.Username,
			&i.User_2.CreatedAt,
			&i.User_2.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
