// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewHasher creates a new instance of Hasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hasher {
	mock := &Hasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Hasher is an autogenerated mock type for the hasher type
type Hasher struct {
	mock.Mock
}

type Hasher_Expecter struct {
	mock *mock.Mock
}

func (_m *Hasher) EXPECT() *Hasher_Expecter {
	return &Hasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type Hasher
func (_mock *Hasher) Hash(s string) ([]byte, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Hasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type Hasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - s string
func (_e *Hasher_Expecter) Hash(s interface{}) *Hasher_Hash_Call {
	return &Hasher_Hash_Call{Call: _e.mock.On("Hash", s)}
}

func (_c *Hasher_Hash_Call) Run(run func(s string)) *Hasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Hasher_Hash_Call) Return(bytes []byte, err error) *Hasher_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Hasher_Hash_Call) RunAndReturn(run func(s string) ([]byte, error)) *Hasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type Hasher
func (_mock *Hasher) Verify(s string, hash []byte) (bool, error) {
	ret := _mock.Called(s, hash)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) (bool, error)); ok {
		return returnFunc(s, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte) bool); ok {
		r0 = returnFunc(s, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = returnFunc(s, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Hasher_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type Hasher_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - s string
//   - hash []byte
func (_e *Hasher_Expecter) Verify(s interface{}, hash interface{}) *Hasher_Verify_Call {
	return &Hasher_Verify_Call{Call: _e.mock.On("Verify", s, hash)}
}

func (_c *Hasher_Verify_Call) Run(run func(s string, hash []byte)) *Hasher_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Hasher_Verify_Call) Return(b bool, err error) *Hasher_Verify_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Hasher_Verify_Call) RunAndReturn(run func(s string, hash []byte) (bool, error)) *Hasher_Verify_Call {
	_c.Call.Return(run)
	return _c
}
