// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AliUnipal/chat/internal/models/user"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewIJWTManager creates a new instance of IJWTManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIJWTManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *IJWTManager {
	mock := &IJWTManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IJWTManager is an autogenerated mock type for the iJWTManager type
type IJWTManager struct {
	mock.Mock
}

type IJWTManager_Expecter struct {
	mock *mock.Mock
}

func (_m *IJWTManager) EXPECT() *IJWTManager_Expecter {
	return &IJWTManager_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function for the type IJWTManager
func (_mock *IJWTManager) CreateToken(ctx context.Context, u user.User) (string, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) (string, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) string); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.User) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IJWTManager_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type IJWTManager_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - u user.User
func (_e *IJWTManager_Expecter) CreateToken(ctx interface{}, u interface{}) *IJWTManager_CreateToken_Call {
	return &IJWTManager_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, u)}
}

func (_c *IJWTManager_CreateToken_Call) Run(run func(ctx context.Context, u user.User)) *IJWTManager_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IJWTManager_CreateToken_Call) Return(s string, err error) *IJWTManager_CreateToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *IJWTManager_CreateToken_Call) RunAndReturn(run func(ctx context.Context, u user.User) (string, error)) *IJWTManager_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function for the type IJWTManager
func (_mock *IJWTManager) VerifyToken(ctx context.Context, token string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IJWTManager_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type IJWTManager_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *IJWTManager_Expecter) VerifyToken(ctx interface{}, token interface{}) *IJWTManager_VerifyToken_Call {
	return &IJWTManager_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token)}
}

func (_c *IJWTManager_VerifyToken_Call) Run(run func(ctx context.Context, token string)) *IJWTManager_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IJWTManager_VerifyToken_Call) Return(uUID uuid.UUID, err error) *IJWTManager_VerifyToken_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *IJWTManager_VerifyToken_Call) RunAndReturn(run func(ctx context.Context, token string) (uuid.UUID, error)) *IJWTManager_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}
