// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewUserAccessor creates a new instance of UserAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserAccessor {
	mock := &UserAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserAccessor is an autogenerated mock type for the userAccessor type
type UserAccessor struct {
	mock.Mock
}

type UserAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *UserAccessor) EXPECT() *UserAccessor_Expecter {
	return &UserAccessor_Expecter{mock: &_m.Mock}
}

// CurrentUserID provides a mock function for the type UserAccessor
func (_mock *UserAccessor) CurrentUserID(ctx context.Context) (uuid.UUID, bool) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentUserID")
	}

	var r0 uuid.UUID
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uuid.UUID, bool)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uuid.UUID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// UserAccessor_CurrentUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentUserID'
type UserAccessor_CurrentUserID_Call struct {
	*mock.Call
}

// CurrentUserID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserAccessor_Expecter) CurrentUserID(ctx interface{}) *UserAccessor_CurrentUserID_Call {
	return &UserAccessor_CurrentUserID_Call{Call: _e.mock.On("CurrentUserID", ctx)}
}

func (_c *UserAccessor_CurrentUserID_Call) Run(run func(ctx context.Context)) *UserAccessor_CurrentUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserAccessor_CurrentUserID_Call) Return(uUID uuid.UUID, b bool) *UserAccessor_CurrentUserID_Call {
	_c.Call.Return(uUID, b)
	return _c
}

func (_c *UserAccessor_CurrentUserID_Call) RunAndReturn(run func(ctx context.Context) (uuid.UUID, bool)) *UserAccessor_CurrentUserID_Call {
	_c.Call.Return(run)
	return _c
}
