// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Message struct {
	ID         uuid.UUID    `db:"id"`
	SenderID   uuid.UUID    `db:"sender_id"`
	ChatID     uuid.UUID    `db:"chat_id"`
	Content    []byte       `db:"content"`
	CreatedAt  time.Time    `db:"created_at"`
	ModifiedAt sql.NullTime `db:"modified_at"`
}
