// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, sender_id, chat_id, content, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMessageParams struct {
	ID        uuid.UUID `db:"id"`
	SenderID  uuid.UUID `db:"sender_id"`
	ChatID    uuid.UUID `db:"chat_id"`
	Content   []byte    `db:"content"`
	CreatedAt time.Time `db:"created_at"`
}

// CreateMessage
//
//	INSERT INTO messages (id, sender_id, chat_id, content, created_at)
//	VALUES ($1, $2, $3, $4, $5)
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.exec(ctx, q.createMessageStmt, createMessage,
		arg.ID,
		arg.SenderID,
		arg.ChatID,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const getMessages = `-- name: GetMessages :many
SELECT id, sender_id, chat_id, content, created_at
FROM messages
WHERE chat_id = $1
`

// GetMessages
//
//	SELECT id, sender_id, chat_id, content, created_at
//	FROM messages
//	WHERE chat_id = $1
func (q *Queries) GetMessages(ctx context.Context, chatID uuid.UUID) ([]Message, error) {
	rows, err := q.query(ctx, q.getMessagesStmt, getMessages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ChatID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
