// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID      `db:"id"`
	ImageUrl  sql.NullString `db:"image_url"`
	FirstName string         `db:"first_name"`
	LastName  sql.NullString `db:"last_name"`
	Username  string         `db:"username"`
	CreatedAt time.Time      `db:"created_at"`
	Password  []byte         `db:"password"`
}
