// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AliUnipal/chat/internal/service/msgsvc/msgrepos"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewChatRepository creates a new instance of ChatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatRepository {
	mock := &ChatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ChatRepository is an autogenerated mock type for the chatRepository type
type ChatRepository struct {
	mock.Mock
}

type ChatRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ChatRepository) EXPECT() *ChatRepository_Expecter {
	return &ChatRepository_Expecter{mock: &_m.Mock}
}

// GetChat provides a mock function for the type ChatRepository
func (_mock *ChatRepository) GetChat(ctx context.Context, id uuid.UUID) (*msgrepos.Chat, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetChat")
	}

	var r0 *msgrepos.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*msgrepos.Chat, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *msgrepos.Chat); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*msgrepos.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ChatRepository_GetChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChat'
type ChatRepository_GetChat_Call struct {
	*mock.Call
}

// GetChat is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ChatRepository_Expecter) GetChat(ctx interface{}, id interface{}) *ChatRepository_GetChat_Call {
	return &ChatRepository_GetChat_Call{Call: _e.mock.On("GetChat", ctx, id)}
}

func (_c *ChatRepository_GetChat_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ChatRepository_GetChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ChatRepository_GetChat_Call) Return(chat *msgrepos.Chat, err error) *ChatRepository_GetChat_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *ChatRepository_GetChat_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*msgrepos.Chat, error)) *ChatRepository_GetChat_Call {
	_c.Call.Return(run)
	return _c
}
